### ISSUE TITLE
[feat]Side Page 개선

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/bmart-7#135]
## Describe the feature
[feat]Side Page 개선

## Todo
- [x] Header 컴포넌트 추가 및 활용
- [x] 클릭한 list만 subtitles열리기
  - [x] subtitles클릭하면 해당 페이지로 이동하기

##  Update
- [x] sublist border-radius 없애기
- [x] 각 리스트 height더 굵게 수정하기
- [x] footer buffer주면서 바닥에 고정시키기
- [x] header max-width:800px; (창 늘려도 800이 넘지않게 조절)
