### ISSUE TITLE
[feat]DetailPage페이지 기능 추가 및 개선

### ISSUE THREAD

**Issue by Blair-0404** [woowa-techcamp-2020/bmart-7#141]
## Describe the feature
DetailPage페이지 기능 추가 및 개선

## Todo
- [x] 구매하기 버튼 클릭시 cart에 해당상품이 담기면서 CartPage로 이동되기

## Update
- [x] 구매하기 버튼 height더 굵게
- [x] favorite 아이콘버튼 image기준으로 다시 position 부여하기
