### ISSUE TITLE
[back] github login 수정

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/bmart-7#24]
## Describe the feature
1. front에서 github login을 진행하면서 backend router에서 필요한 부분들 수정
2. prisma를 통해 실제 DB 연동
## Todo
- [x] api/github-login/callback 삭제
- [x] jwt token을 만들어 json으로 전달
- [x] id를 통해 해당 user를 db에서 탐색
- [x] user가 없다면 user 정보를 DB에 저장
