### ISSUE TITLE
[8월 11일] Todo

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/bmart-7#3]
# Todo

## 최범수
- [x] graphQL에 passport 적용하는 법 + OAuth

## 박지환
- [x] client에서 GraphQL 사용하는 법
- [x] JWT에 대해

## 김영지
- [x] Typescript
- [ ] axios 

## 공통
- [ ] front 설정 정리해오기
- [x] GraphQL, Prisma 적용하는 법 공부
- [ ] OAuth에 맞는 User Table 생각해오기
