### ISSUE TITLE
[front]MainCatrgoryContainer작업

### ISSUE THREAD

**Issue by Blair-0404** [woowa-techcamp-2020/bmart-7#53]
## Describe the feature
* 컴포넌트의 구조에 대해 먼저 생각해보고 메인 카테고리 부분에 대한 작업 구현
## Todo
- [x] 아이콘 이미지들 images/mainicons folder에 셋팅
- [x] MainCatrgoryContainer 생성 및 작업
- [x] MainCatrgoryItem 생성 및 작업 - MainCatrgoryContainer에서 map을 돌며 MainCatrgoryItem를 생성하고 props전달

## Update
- [x] Carousel 폴더 common으로 이동
- [x] LoginPage folder생성 후  LoginPage.tex->index.tsx로 변경
- [x]  /login페이지 url에 mainpage인 "/"도 포함되어있어 페이지 두개가 같이 보이는 문제가 보였다.
      -> App.tsx에서  메인 페이지 라우트 부분에 exact추가 -> <Route path=“/” exact> 
      exact를 추가해야 정확히 "/"일 때만 메인페이지에 해당하는 컴포넌트들이 그려진다고 합니다.!
