### ISSUE TITLE
[front] CategoryPreviewSection 컴포넌트 구현

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/bmart-7#63]
## Describe the feature
카테고리를 누르면 해당 카테고리에 해당하는 10개의 상품이 나오는 CategoryPreviewSection 컴포넌트 구현
## Todo
- [ ] ProductList 컴포넌트 재사용
- [ ] 카테고리를 선택할 수 있는 Header 구현
- [ ] 카테고리를 선택하면 해당 카테고리의 Product를 보여주도록
- [ ] 각각의 카테고리의 상품을 보여주는 CategoryPreview 컴포넌트 구현 및 재사용
